nyc_parking_violations:
  target: dev
  outputs:
   dev:
     type: postgres
     host: postgres
     user: "{{env_var('AIRFLOW_POSTGRES_USER')}}"
     password: "{{env_var('AIRFLOW_POSTGRES_PASSWORD')}}"
     dbname: postgres
     port: 5432
