version: 2

seeds:
  - name: parking_violations_issued_fiscal_year_2023_sample
    config:
      column_types:
        Summons_Number: integer
        Registration_State: varchar
        Plate_Type: varchar
        Issue_Date: varchar
        Violation_Code: integer
        Vehicle_Body_Type: varchar
        Vehicle_Make: varchar
        Issuing_Agency: varchar
        Vehicle_Expiration_Date: varchar
        Violation_Location: varchar
        Violation_Precinct: integer
        Issuer_Precinct: integer
        Issuer_Code: integer
        Issuer_Command: varchar
        Issuer_Squad: varchar
        Violation_Time: varchar
        Time_First_Observed: varchar
        Violation_County: varchar
        Violation_In_Front_Of_Or_Opposite: varchar
        Date_First_Observed: varchar
        Law_Section: integer
        Sub_Division: varchar
        Violation_Legal_Code: varchar
        Days_Parking_In_Effect: varchar
        From_Hours_In_Effect: varchar
        To_Hours_In_Effect: varchar
        Vehicle_Color: varchar
        Unregistered_Vehicle: varchar
        Vehicle_Year: integer
        Meter_Number: varchar
        Feet_From_Curb: integer
        No_Standing_or_Stopping_Violation: varchar
        Hydrant_Violation: varchar
        Double_Parking_Violation: varchar

  - name: dof_parking_violation_codes
    config:
      column_types:
        CODE: integer
        DEFINITION: varchar
        Manhattan_96th_St_and_below: integer
        All_Other_Areas: integer
