version: 2

seeds:
  - name: parking_violations_issued_fiscal_year_2023_sample
    config:
      column_types:
        summons_number: bigint
        registration_state: varchar
        plate_type: varchar
        issue_date: varchar
        violation_code: integer
        vehicle_body_type: varchar
        vehicle_make: varchar
        issuing_agency: varchar
        vehicle_expiration_date: varchar
        violation_location: varchar
        violation_precinct: integer
        issuer_precinct: integer
        issuer_code: integer
        issuer_command: varchar
        issuer_squad: varchar
        violation_time: varchar
        time_first_observed: varchar
        violation_county: varchar
        violation_in_front_of_or_opposite: varchar
        date_first_observed: varchar
        law_section: integer
        sub_division: varchar
        violation_legal_code: varchar
        days_parking_in_effect: varchar
        from_hours_in_effect: varchar
        to_hours_in_effect: varchar
        vehicle_color: varchar
        unregistered_vehicle: varchar
        vehicle_year: integer
        meter_number: varchar
        feet_from_curb: integer
        no_standing_or_stopping_violation: varchar
        hydrant_violation: varchar
        double_parking_violation: varchar

  - name: dof_parking_violation_codes
    config:
      column_types:
        code: integer
        definition: varchar
        manhattan_96th_st_and_below: integer
        all_other_areas: integer
