version: 2

seeds:
  - name: parking_violations_issued_fiscal_year_2023_sample
    config:
      column_types:
        "Summons Number": number
        "Registration State": text
        "Plate Type": text
        "Issue Date": text
        "Violation Code": number
        "Vehicle Body Type": text
        "Vehicle Make": text
        "Issuing Agency": text
        "Vehicle Expiration Date": text
        "Violation Location": text
        "Violation Precinct": number
        "Issuer Precinct": number
        "Issuer Code": number
        "Issuer Command": text
        "Issuer Squad": text
        "Violation Time": text
        "Time First Observed": text
        "Violation County": text
        "Violation In Front Of Or Opposite": text
        "Date First Observed": text
        "Law Section": number
        "Sub Division": text
        "Violation Legal Code": text
        "Days Parking In Effect": text
        "From Hours In Effect": text
        "To Hours In Effect": text
        "Vehicle Color": text
        "Unregistered Vehicle?": text
        "Vehicle Year": number
        "Meter Number": text
        "Feet From Curb": number
        "No Standing or Stopping Violation": text
        "Hydrant Violation": text
        "Double Parking Violation": text

  - name: dof_parking_violation_codes
    config:
      column_types:
        CODE: number
        DEFINITION: text
        "Manhattan 96th St. & below": number
        "All Other Areas": number
