SELECT
    summons_number,
    Registration_State,
    Plate_Type,
    Vehicle_Body_Type,
    Vehicle_Make,
    Vehicle_Expiration_Date,
    Vehicle_Color,
    Vehicle_Year
FROM
    {{ref('silver_parking_violations')}}
