version: 2

seeds:
  - name: parking_violations_issued_fiscal_year_2023_sample
    columns:
      - name: summons_number
        alias: "Summons Number"
      - name: registration_state
        alias: "Registration State"
      - name: plate_type
        alias: "Plate Type"
      - name: issue_date
        alias: "Issue Date"
      - name: violation_code
        alias: "Violation Code"
      - name: vehicle_body_type
        alias: "Vehicle Body Type"
      - name: vehicle_make
        alias: "Vehicle Make"
      - name: issuing_agency
        alias: "Issuing Agency"
      # ... and so on for all columns

  - name: dof_parking_violation_codes
    columns:
      - name: code
        alias: CODE
      - name: definition
        alias: DEFINITION
      - name: manhattan_96th_st_below
        alias: "Manhattan 96th St. & below"
      - name: all_other_areas
        alias: "All Other Areas"
